// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqzgovjrwwbgukkgvsuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxemdvdmpyd3diZ3Vra2d2c3V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4Mjc4MDgsImV4cCI6MjA2NTQwMzgwOH0.vyhfBPOF3VR2E_Ww5YWi7yQ-qCsY_QXA6VBC3MhkQw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);